# Generated by Django 3.1.3 on 2020-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
