# Generated by Django 3.1.3 on 2020-12-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_picture_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture_image',
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_name',
            field=models.TextField(primary_key='True', serialize=False),
        ),
    ]
