# Generated by Django 3.1.3 on 2020-12-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0003_auto_20201228_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
